# Generated by Django 6.0.6 on 2026-06-30 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(help_text='kg, litre, sac...', max_length=20)),
                ('production_date', models.DateField()),
                ('reception_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('RECEIVED', 'Réceptionnée'), ('REJECTED', 'Refusée')], default='PENDING', max_length=20)),
                ('observation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productions', to='products.product')),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='accounts.producteur')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_productions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Production',
                'verbose_name_plural': 'Productions',
                'ordering': ['-production_date'],
            },
        ),
    ]
