# Generated by Django 6.0.6 on 2026-07-07 13:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocieteLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('responsable', models.CharField(blank=True, max_length=150)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Société de livraison',
                'verbose_name_plural': 'Sociétés de livraison',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True)),
                ('adresse_livraison', models.TextField()),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Recalculé côté serveur à partir des lignes de commande.', max_digits=12)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de paiement'), ('EN_PREPARATION', 'En préparation'), ('PRETE', 'Prête pour collecte'), ('EN_LIVRAISON', 'En livraison'), ('LIVREE', 'Livrée'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.PROTECT, related_name='commandes_passees', to=settings.AUTH_USER_MODEL)),
                ('livreur', models.ForeignKey(blank=True, limit_choices_to={'role': 'LIVREUR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_livrees', to=settings.AUTH_USER_MODEL)),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_recues', to='accounts.producteur')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('prix', models.DecimalField(decimal_places=2, editable=False, help_text='Prix figé au moment de la commande.', max_digits=10)),
                ('sous_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='market.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_commande', to='catalog.produit')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
            },
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', "En attente d'un livreur (pool)"), ('EN_COURS', 'En cours'), ('LIVREE', 'Livrée (déclarée par le livreur)'), ('CONFIRMEE', 'Confirmée reçue')], default='EN_ATTENTE', max_length=20)),
                ('date_prise', models.DateTimeField(blank=True, null=True)),
                ('date_livraison', models.DateTimeField(blank=True, null=True)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='market.commande')),
                ('confirmee_par', models.ForeignKey(blank=True, help_text="Le client lui-même, ou l'admin si le client ne répond pas.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons_confirmees', to=settings.AUTH_USER_MODEL)),
                ('livreur', models.ForeignKey(blank=True, limit_choices_to={'role': 'LIVREUR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to=settings.AUTH_USER_MODEL)),
                ('societe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to='market.societelivraison')),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('PAYEE', 'Payée')], default='EN_ATTENTE', max_length=20)),
                ('livreur', models.ForeignKey(limit_choices_to={'role': 'LIVREUR'}, on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to=settings.AUTH_USER_MODEL)),
                ('livraison', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='market.livraison')),
            ],
            options={
                'verbose_name': 'Commission livreur',
                'verbose_name_plural': 'Commissions livreurs',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moyen', models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money (Orange/Moov)'), ('WAVE', 'Wave'), ('CARTE', 'Carte prépayée')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYE', 'Payé'), ('ECHEC', 'Échec')], default='EN_ATTENTE', max_length=20)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='market.commande')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='paniers', to=settings.AUTH_USER_MODEL)),
                ('producteur', models.ForeignKey(blank=True, help_text="Renseigné automatiquement à l'ajout du premier article.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paniers', to='accounts.producteur')),
            ],
            options={
                'verbose_name': 'Panier',
                'verbose_name_plural': 'Paniers',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PanierArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('prix', models.DecimalField(decimal_places=2, help_text="Prix unitaire au moment de l'ajout (peut différer du prix courant du produit).", max_digits=10)),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='market.panier')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.produit')),
            ],
            options={
                'verbose_name': 'Article du panier',
                'verbose_name_plural': 'Articles du panier',
            },
        ),
        migrations.CreateModel(
            name='Versement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant brut de la commande.', max_digits=12)),
                ('commission_plateforme', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_net', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VERSE', 'Versé')], default='EN_ATTENTE', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date_versement', models.DateTimeField(blank=True, null=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='versement', to='market.commande')),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versements', to='accounts.producteur')),
            ],
            options={
                'verbose_name': 'Versement producteur',
                'verbose_name_plural': 'Versements producteurs',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['client', '-date_commande'], name='idx_commande_client_date'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['producteur', 'statut'], name='idx_commande_producteur_statut'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['livreur', 'statut'], name='idx_commande_livreur_statut'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['livreur', 'statut'], name='idx_commission_livreur_statut'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['statut'], name='idx_paiement_statut'),
        ),
        migrations.AddIndex(
            model_name='panier',
            index=models.Index(fields=['client'], name='idx_panier_client'),
        ),
        migrations.AddConstraint(
            model_name='panier',
            constraint=models.UniqueConstraint(fields=('client', 'producteur'), name='un_panier_actif_par_producteur'),
        ),
        migrations.AddConstraint(
            model_name='panierarticle',
            constraint=models.UniqueConstraint(fields=('panier', 'produit'), name='un_produit_une_fois_par_panier'),
        ),
        migrations.AddIndex(
            model_name='livraison',
            index=models.Index(fields=['statut'], name='idx_livraison_statut'),
        ),
        migrations.AddIndex(
            model_name='livraison',
            index=models.Index(fields=['livreur', 'statut'], name='idx_livraison_livreur_statut'),
        ),
        migrations.AddIndex(
            model_name='versement',
            index=models.Index(fields=['producteur', 'statut'], name='idx_versement_prod_statut'),
        ),
    ]
