# Generated by Django 6.0.6 on 2026-07-07 13:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='formations/documents/')),
                ('video', models.URLField(blank=True, help_text='Lien externe (YouTube, etc.) si applicable.')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('publie_par', models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations_publiees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SujetForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('epingle', models.BooleanField(default=False, help_text="Mis en avant par l'administrateur.")),
                ('ferme', models.BooleanField(default=False, help_text="Fermé aux nouvelles réponses par l'administrateur.")),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sujets_forum', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sujet du forum',
                'verbose_name_plural': 'Sujets du forum',
                'ordering': ['-epingle', '-date'],
            },
        ),
        migrations.CreateModel(
            name='ReponseForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_forum', to=settings.AUTH_USER_MODEL)),
                ('sujet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='community.sujetforum')),
            ],
            options={
                'verbose_name': 'Réponse du forum',
                'verbose_name_plural': 'Réponses du forum',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='avis', to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='catalog.produit')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['produit', '-date'], name='idx_avis_produit_date')],
                'constraints': [models.UniqueConstraint(fields=('produit', 'client'), name='un_avis_par_client_et_produit')],
            },
        ),
        migrations.CreateModel(
            name='SuiviFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progression', models.PositiveSmallIntegerField(default=0, help_text='Pourcentage de progression (0-100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('terminee', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='community.formation')),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis_formation', to='accounts.producteur')),
            ],
            options={
                'verbose_name': 'Suivi de formation',
                'verbose_name_plural': 'Suivis de formation',
                'indexes': [models.Index(fields=['producteur', 'terminee'], name='idx_suivi_producteur_termine')],
                'constraints': [models.UniqueConstraint(fields=('formation', 'producteur'), name='un_suivi_par_producteur_et_formation')],
            },
        ),
        migrations.AddIndex(
            model_name='sujetforum',
            index=models.Index(fields=['-epingle', '-date'], name='idx_sujet_epingle_date'),
        ),
        migrations.AddIndex(
            model_name='reponseforum',
            index=models.Index(fields=['sujet', 'date'], name='idx_reponse_sujet_date'),
        ),
    ]
