# Generated by Django 6.0.6 on 2026-07-19 01:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalactivite',
            options={'ordering': ['-date'], 'verbose_name': 'Journal activité', 'verbose_name_plural': 'Journaux activités'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-date'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='parametre',
            options={'verbose_name': 'Paramètre plateforme', 'verbose_name_plural': 'Paramètres plateforme'},
        ),
        migrations.RemoveConstraint(
            model_name='utilisateur',
            name='type_client_uniquement_client',
        ),
        migrations.RenameIndex(
            model_name='utilisateur',
            new_name='accounts_ut_role_82a49c_idx',
            old_name='idx_utilisateur_role',
        ),
        migrations.RenameIndex(
            model_name='utilisateur',
            new_name='accounts_ut_role_d3e86f_idx',
            old_name='idx_utilisateur_role_actif',
        ),
        migrations.AlterField(
            model_name='journalactivite',
            name='action',
            field=models.CharField(max_length=100, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='journalactivite',
            name='adresse_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP'),
        ),
        migrations.AlterField(
            model_name='journalactivite',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='journalactivite',
            name='objet',
            field=models.CharField(blank=True, max_length=150, verbose_name='Objet'),
        ),
        migrations.AlterField(
            model_name='journalactivite',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_activite', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='lu',
            field=models.BooleanField(default=False, verbose_name='Lu'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='titre',
            field=models.CharField(max_length=150, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='parametre',
            name='commission_livreur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Commission livreur'),
        ),
        migrations.AlterField(
            model_name='parametre',
            name='commission_plateforme',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Commission plateforme (%)'),
        ),
        migrations.AlterField(
            model_name='parametre',
            name='devise',
            field=models.CharField(default='FCFA', max_length=10, verbose_name='Devise'),
        ),
        migrations.AlterField(
            model_name='parametre',
            name='maintenance',
            field=models.BooleanField(default=False, verbose_name='Mode maintenance'),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='date_creation',
            field=models.DateField(auto_now_add=True, verbose_name='Date création'),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='nom_exploitation',
            field=models.CharField(max_length=150, verbose_name='Nom exploitation'),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='producteur', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Compte actif'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='adresse',
            field=models.TextField(blank=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='autre_precision',
            field=models.CharField(blank=True, max_length=100, verbose_name='Autre précision'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date création'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Adresse email'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='utilisateurs/photos/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='premiere_connexion',
            field=models.BooleanField(default=False, verbose_name='Première connexion'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='prenom',
            field=models.CharField(max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('PRODUCTEUR', 'Producteur'), ('CLIENT', 'Client'), ('LIVREUR', 'Livreur')], db_index=True, default='CLIENT', max_length=20, verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='type_client',
            field=models.CharField(blank=True, choices=[('RESTAURANT', 'Restaurant'), ('REVENDEUR', 'Revendeur / Transformateur'), ('AUTRE', 'Autre')], max_length=20, null=True, verbose_name='Type client'),
        ),
    ]
