# Generated by Django 6.0.6 on 2026-07-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_journalactivite_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametre',
            name='commission_livreur',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='Commission livreur (%)'),
        ),
    ]
