# Generated by Django 6.0.6 on 2026-07-07 13:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['nom'],
                'indexes': [models.Index(fields=['nom'], name='idx_categorie_nom')],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unite', models.CharField(default='kg', help_text='kg, litre, sac, pièce...', max_length=20)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('type_produit', models.CharField(choices=[('FRAIS', 'Produit frais'), ('TRANSFORME', 'Produit transformé'), ('INTRANT', 'Intrant agroécologique')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/')),
                ('valide', models.BooleanField(default=False, help_text='Validation admin requise avant apparition dans le catalogue public.')),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('disponible', models.BooleanField(default=True, help_text='Bascule rapide indépendante de la validation admin.')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='catalog.categorie')),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='accounts.producteur')),
                ('valide_par', models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ProduitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='produits/galerie/')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.produit')),
            ],
            options={
                'verbose_name': 'Image produit',
                'verbose_name_plural': 'Images produit',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Ex: BIO SPG, CNABio...', max_length=100)),
                ('numero', models.CharField(blank=True, max_length=100)),
                ('document', models.FileField(blank=True, null=True, upload_to='certifications/documents/')),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, help_text="Date d'expiration de la certification.", null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE', max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='accounts.producteur')),
                ('valide_par', models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certifications_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['-date_debut'],
                'indexes': [models.Index(fields=['producteur', 'statut'], name='idx_certif_producteur_statut'), models.Index(fields=['statut', 'date_fin'], name='idx_certif_statut_date_fin')],
                'constraints': [models.CheckConstraint(condition=models.Q(('date_fin__isnull', True), ('date_debut__isnull', True), ('date_fin__gte', models.F('date_debut')), _connector='OR'), name='certification_date_fin_apres_date_debut')],
            },
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['producteur', 'valide', 'disponible'], name='idx_produit_prod_valide_dispo'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['categorie'], name='idx_produit_categorie'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['nom'], name='idx_produit_nom'),
        ),
        migrations.AddConstraint(
            model_name='produit',
            constraint=models.CheckConstraint(condition=models.Q(('prix__gte', 0)), name='produit_prix_positif'),
        ),
    ]
