# Generated by Django 6.0.6 on 2026-07-10 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='valide_par',
        ),
    ]
